-- Migration 009: First-access human approval (pending_grants) +
-- daemon attestation (daemon_sessions, allowed_daemon_versions).
--
-- Implements UNCERTAINTIES.md #16 (daemon token persistence + first-access
-- approval) and #17 (daemon attestation header).
--
-- pending_grants tracks every (agent_id, project_name, scope) discover request
-- that requires human approval the first time it's seen. After approval, the
-- row's status is set to 'approved' with the requested scope; subsequent
-- discover requests within `auto_approval_until` automatically pass without a
-- new dashboard alert. A scope expansion (set difference grows) re-triggers
-- a 'pending' row.
CREATE TABLE IF NOT EXISTS pending_grants (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    project_name TEXT NOT NULL,
    namespace TEXT NOT NULL,
    -- JSON array of secret key_paths the agent asked for.
    requested_keys TEXT NOT NULL DEFAULT '[]',
    -- JSON array of key_paths actually approved by the operator. NULL until decided.
    approved_keys TEXT,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'denied', 'expired')),
    requested_at TEXT NOT NULL DEFAULT (datetime('now')),
    decided_at TEXT,
    -- Free-form admin identifier. Today this is "admin" for the bootstrap
    -- token; with #18 multi-user RBAC it will be the admin's user id.
    decided_by TEXT,
    -- After approval, future (agent_id, project, scope-subset) discovers within
    -- this window auto-pass. Default 30 days from decided_at (set by handler).
    auto_approval_until TEXT,
    source_ip TEXT
);

CREATE INDEX IF NOT EXISTS idx_pending_grants_agent_project
    ON pending_grants (agent_id, project_name);
CREATE INDEX IF NOT EXISTS idx_pending_grants_status
    ON pending_grants (status, requested_at);

-- daemon_sessions: every running daemon registers an ephemeral attestation
-- public key (Ed25519). The matching private key lives only in the daemon's
-- memory (never written to disk) and signs every sensitive HTTP request via
-- the X-Daemon-Attestation header so the server can pin a request to a
-- specific running daemon process.
CREATE TABLE IF NOT EXISTS daemon_sessions (
    -- session_id is a server-issued UUID returned by /daemon/attest.
    session_id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    -- base64url-encoded Ed25519 public key generated by the daemon at boot.
    attestation_pub TEXT NOT NULL,
    -- SHA-256 hex of the daemon binary that registered. Must appear in
    -- allowed_daemon_versions or the registration is rejected.
    binary_sha256 TEXT NOT NULL,
    -- daemon-self-reported version string ("cortex-daemon 0.1.0"). Advisory.
    daemon_version TEXT,
    -- daemon-self-reported PID + UID. Advisory.
    daemon_pid INTEGER,
    daemon_uid INTEGER,
    hostname TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at TEXT NOT NULL,
    revoked_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_daemon_sessions_agent
    ON daemon_sessions (agent_id);
CREATE INDEX IF NOT EXISTS idx_daemon_sessions_active
    ON daemon_sessions (revoked_at, expires_at);

-- allowed_daemon_versions: operators populate this table from the project's
-- signed release manifest. The /daemon/attest handler refuses any binary
-- whose SHA-256 is not in this allowlist. An empty table is interpreted as
-- "no allowlist enforced" so existing deployments don't break — operators
-- opt in by inserting their first row.
CREATE TABLE IF NOT EXISTS allowed_daemon_versions (
    binary_sha256 TEXT PRIMARY KEY,
    version TEXT,
    description TEXT,
    -- 1 = enforced; 0 = soft-deprecated (still allowed but warns in audit log).
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Replay protection for daemon attestation jti — every X-Daemon-Attestation
-- header carries a jti unique to the request. We accept any jti once within
-- the 5-minute timestamp window and reject duplicates.
CREATE TABLE IF NOT EXISTS daemon_attest_seen_jti (
    jti TEXT PRIMARY KEY,
    seen_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_daemon_attest_seen_jti_time
    ON daemon_attest_seen_jti (seen_at);
